#!/bin/bash
# /etc/init.d/buttons

### BEGIN INIT INFO
# Provides:          buttons
# Required-Start:    $syslog $network
# Required-Stop:     $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to start buttons
### END INIT INFO


case "$1" in
    start)
        cd /home/pi/pibuttons
        /usr/bin/sudo -u pi -H /home/pi/pibuttons/update-and-run.sh

        ;;
    stop)
        echo "Stopping buttons"
        killall buttons

        ;;
    *)
        echo "Usage: /etc/init.d/buttons start|stop"
        exit 1
        ;;
esac
exit 0
